name: paisa
description: A Flutter and Dart plugin for converting currencies and getting the latest exchange rates. Supports 161 currencies.
version: 0.0.6
repository: 'https://github.com/icodelifee/paisa.dart'
issue_tracker: https://github.com/icodelifee/paisa.dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.3
  test: