// ignore_for_file: constant_identifier_names
// ignoring this linter rule because the names are the same as the API

enum Currency {
  AFN('Afghan Afghani'),
  ALL('Albanian Lek'),
  DZD('Algerian Dinar'),
  AOA('Angolan Kwanza'),
  ARS('Argentine Peso'),
  AMD('Armenian Dram'),
  AWG('Aruban Florin'),
  AUD('Australian Dollar'),
  AZN('Azerbaijani Manat'),
  BSD('Bahamian Dollar'),
  BHD('Bahraini Dinar'),
  BBD('Barbadian Dollar'),
  BDT('Bangladeshi Taka'),
  BYN('Belarusian Ruble'),
  BZD('Belize Dollar'),
  BMD('Bermudian Dollar'),
  BTN('Bhutanese Ngultrum'),
  BOB('Bolivian Boliviano'),
  BAM('Bosnia-Herzegovina Convertible Mark'),
  BWP('Botswana Pula'),
  BRL('Brazilian Real'),
  BND('Brunei Dollar'),
  BGN('Bulgarian Lev'),
  BIF('Burundi Franc'),
  XPF('CFP Franc'),
  KHR('Cambodian Riel'),
  CAD('Canadian Dollar'),
  CUP('Cuban Peso'),
  CVE('Cape Verdean Escudo'),
  KYD('Cayman Islands Dollar'),
  FCFA('Central African CFA Franc'),
  CLP('Chilean Peso'),
  CLF('Chilean Unit of Account (UF)'),
  CNY('Chinese Yuan'),
  COP('Colombian Peso'),
  CF('Congolese Franc'),
  CDF('Congolese Franc'),
  CRC('Costa Rican Colón'),
  HRK('Croatian Kuna'),
  CUC('Cuban Convertible Peso'),
  CZK('Czech Koruna'),
  DKK('Danish Krone'),
  DJF('Djiboutian Franc'),
  DOP('Dominican Peso'),
  XCD('East Caribbean Dollar'),
  EGP('Egyptian Pound'),
  ETB('Ethiopian Birr'),
  ERN('Eritrean Nakfa'),
  EUR('Euro'),
  FJD('Fijian Dollar'),
  FKP('Falkland Islands Pound'),
  GMD('Gambian Dalasi'),
  GEL('Georgian Lari'),
  GHS('Ghanaian Cedi'),
  GTQ('Guatemalan Quetzal'),
  GIN('Guinean Franc'),
  GIP('Gibraltar pound'),
  GNF('Guinean Franc'),
  GYD('Guyanese Dollar'),
  HTG('Haitian Gourde'),
  HNL('Honduran Lempira'),
  HKD('Hong Kong Dollar'),
  HUF('Hungarian Forint'),
  ISK('Icelandic Króna'),
  INR('Indian Rupee'),
  IDR('Indonesian Rupiah'),
  IRR('Iranian Rial'),
  IQD('Iraqi Dinar'),
  ILS('Israeli New Sheqel'),
  JMD('Jamaican Dollar'),
  JPY('Japanese Yen'),
  JOD('Jordanian Dinar'),
  KZT('Kazakhstani Tenge'),
  KES('Kenyan Shilling'),
  KWD('Kuwaiti Dinar'),
  KGS('Kyrgyzstani Som'),
  KPW('North Korean Won'),
  KMF('Comorian franc'),
  LAK('Lao Kip'),
  LBP('Lebanese Pound'),
  LSL('Lesotho Loti'),
  LRD('Liberian Dollar'),
  LYD('Libyan Dinar'),
  MOP('Macanese Pataca'),
  MKD('Macedonian Denar'),
  MWK('Malawian Kwacha'),
  MYR('Malaysian Ringgit'),
  MUR('Mauritian Rupee'),
  MXN('Mexican Peso'),
  MVR('Maldivian Rufiyaa'),
  MDL('Moldovan Leu'),
  MNT('Mongolian Tögrög'),
  MAD('Moroccan Dirham'),
  MZN('Mozambican Metical'),
  MMK('Myanmar Kyat'),
  MRU('Mauritanian ouguiya'),
  NAD('Namibian Dollar'),
  NPR('Nepalese Rupee'),
  ANG('Netherlands Antillean Guilder'),
  TWD('New Taiwan Dollar'),
  NZD('New Zealand Dollar'),
  NIO('Nicaraguan Córdoba'),
  NGN('Nigerian Naira'),
  NOK('Norwegian Krone'),
  OMR('Omani Rial'),
  PKR('Pakistani Rupee'),
  PAB('Panamanian Balboa'),
  PGK('Papua New Guinean Kina'),
  PYG('Paraguayan Guaraní'),
  PEN('Peruvian Nuevo Sol'),
  PHP('Philippine Peso'),
  PLN('Polish Złoty'),
  QAR('Qatari Riyal'),
  RON('Romanian Leu'),
  RUB('Russian Ruble'),
  RWF('Rwandan Franc'),
  WST('Samoan Tala'),
  STD('São Tomé and Príncipe Dobra'),
  SAR('Saudi Riyal'),
  RSD('Serbian Dinar'),
  SCR('Seychellois Rupee'),
  SLL('Sierra Leonean Leone'),
  SGD('Singapore Dollar'),
  SSP('South Sudanese Pound'),
  SBD('Solomon Islands Dollar'),
  SOS('Somali Shilling'),
  ZAR('South African Rand'),
  KRW('South Korean Won'),
  LKR('Sri Lankan Rupee'),
  SDG('Sudanese Pound'),
  SZL('Swazi Lilangeni'),
  SEK('Swedish Krona'),
  SRD('Suriname Dollar'),
  SHP('Saint Helena Pound'),
  SVC('Salvadoran colón'),
  CHF('Swiss Franc'),
  SYP('Syrian Pound'),
  TJS('Tajikistani Somoni'),
  THB('Thai Baht'),
  TTD('Trinidad and Tobago Dollar'),
  TOP('Tongan paanga'),
  TZS('Tanzanian shilling'),
  TND('Tunisian Dinar'),
  TRY('Turkish Lira'),
  TMT('Turkmenistani Manat'),
  UGX('Ugandan Shilling'),
  UAH('Ukrainian Hryvnia'),
  AED('United Arab Emirates Dirham'),
  GBP('British Pound'),
  USD('United States Dollar'),
  UYU('Uruguayan Peso'),
  UZS('Uzbekistan Som'),
  VUV('Vanuatu Vatu'),
  VEF('Venezuelan Bolívar'),
  VND('Vietnamese Đồng'),
  XAF('Central African CFA franc'),
  XOF('West African CFA franc'),
  YER('Yemeni Rial'),
  ZMW('Zambian Kwacha'),
  ZWL('Zimbabwean Dollar');

  const Currency(this.currencyName);
  final String currencyName;
}
